### ISSUE TITLE
Where to modify the environment variables?

### ISSUE THREAD

**Issue by CrowRGG** [ever-co/ever-traduora#237] opened 2021-06-29 06:45 UTC
I am using traduora there days, and I meet some problems.
Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'root'@'localhost' (using password: NO)
I check the official doc, and it reminds me that need to change environment variables.
But I really no idea how to change it?
Do I need to create a new profile? or something?
Centos 7.6 + Mysql 5.7
Please help me!

**Comment by evereq** [comment] 2021-06-29 12:03
You can see list of env vars Traduora read which responsible for connectivity to DB here: https://github.com/ever-co/ever-traduora/blob/develop/api/src/config.ts#L50. 

Structure is simple, first goes env var name (e.g. `TR_DB_USER`) and after `||` goes default value, e.g. `root`. 

```
 host: env.TR_DB_HOST || '127.0.0.1',
 port: parseInt(env.TR_DB_PORT, 10) || 3306,
 username: env.TR_DB_USER || 'root',
 password: env.TR_DB_PASSWORD || '',
 database: env.TR_DB_DATABASE || 'tr_dev',
```

Hope that helps, I am closing ticket as it's not a bug, but a question about setup.

**Closed by evereq** 2021-06-29 12:03 UTC
Labels: bug, help wanted

**Comment by CrowRGG** [comment] 2021-06-29 12:12
Thank you!
But when I modified it, still the same problem.
password: env.TR_DB_PASSWORD || '123',
Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'root'@'localhost' (using password: NO)

**Comment by evereq** [comment] 2021-06-29 12:19
you need to modify the env variable, not the source code. I.e. you need to set env var to specific value, depending on your OS. 
All parameters are imported, like username ("root") or password to be set correctly so software can connect to DB. 
I suggest to try some other tool (e.g. https://www.mysql.com/products/workbench/) to connect to your DB first with parameters you set, e.g. with user "root" and password "123" (which you seems hardcoded in the code). and see if that software can connect or not.

**Comment by evereq** [comment] 2021-06-29 21:25
sorry I mean how you set env var depends on your OS. For Linux, you do it one way, for Windows another, etc. 
If you can connect via Navicat it's really weird you can't connect from code as long as you set correctly host, username and password (described in the answers above).

**Comment by CrowRGG** [comment] 2021-06-30 04:32
Is that mean I do need to change any source code according to your answers, what I need just to type TR_DB_PASSWORD='123' in cmd, maybe this is the key.
Thank you again!
