### ISSUE TITLE
Limitation of use ?

### ISSUE THREAD

**Issue by JBR69** [ever-co/ever-traduora#170] opened 2020-10-20 09:34 UTC
What does "Current usage" mean in project settings ?
Does this mean that we are limited to 100,000 labels (all locales combined) ?

**Comment by anthonynsimon** [comment] 2020-10-29 10:04
This is a legacy of the time when there was a managed version too, it will be removed in a subsequent release.

There is no real limitation in use.

If you can't wait for the release when we change this, you can simply edit the limit on your database. There will be a plan entry called `open-source`with a limit of 100k, you can change it to whatever you want.

**Comment by evereq** [comment] 2021-05-23 20:48
Closing as no limits will be in AGPL version (except of course limitations caused by the license itself)

**Closed by evereq** 2021-05-23 20:48 UTC
Labels: feature
